puts "The student of Villians Academy"
puts "----------------"
puts "Dr. Hannibal Lecter"
puts "Darth Varder"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the west"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Jeffrey Baraheon"
puts "Norman Bates"